apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-spa
spec:
  selector:
    matchLabels:
      app: live-spa

  template:
    metadata:
      labels:
        app: live-spa
    spec:
      containers:
        - name: live-spa
          image: wesleywillians/maratona2-live-spa:latest
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: live-spa-service
  labels:
    app: live-spa-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: live-spa