version: '3'

services:

  codebot:
    build: .
    container_name: micro-codebot
    ports:
      - 50051:50051
    environment:
      WAIT_HOSTS: db:5432
      WAIT_HOSTS_TIMEOUT: 300

  db:
   image: postgres:9.4
   restart: always
   tty: true
   volumes:
     - pgdata:/var/lib/postgresql/data
   environment:
     - POSTGRES_PASSWORD=root
     - POSTGRES_DB=codebot
   ports:
     - "5433:5432"

volumes:
  pgdata:
    external: true
