version: '3'

services:

    desafio02:
        build: ./
        entrypoint: ./.docker/entrypoint.sh
        container_name: desafio02_full-cycle
        environment:
        - CHOKIDAR_USEPOLLING=true
        ports:
        - 3000:3000
        - 9000:9000
        - 5000:5000
        volumes:
        - .:/home/node/app
        networks:
        - app-network

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: desafio02-db
        restart: always
        tty: true
        ports:
        - 33006:3306
        volumes:
        - ./.docker/dbdata:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
        - MYSQL_DATABASE=desafio02
        networks:
        - app-network

networks:
    app-network:
        driver: bridge      